### ISSUE TITLE
Consider a11y in code snippets

### ISSUE THREAD

**Issue by HugoGiraudel** [cjcenizal/flexbox-patterns#3]
A lot of people are likely to just copy and paste your HTML code snippets into their project. Because of this, I would recommend considering accessibility in the HTML (roles, meaningful markup, and so on).

**Comment by cjcenizal** [comment]
Thanks, Hugo! I really want to keep the focus of this project on how to use flexbox to build UI components, and I'm afraid that adding anything not flexbox-related to the examples will dilute that focus. 

But I think you have a good point about the possibility that people will copy-paste examples, and that will propagate bad practices. The best compromise I can think of is to add some notes to the README and the website, stating that these examples shouldn't be cut-and-pasted because they lack the best practices you mention.

**Comment by HugoGiraudel** [comment]
Sounds like a decent compromise I guess.

**Comment by cjcenizal** [comment]
Updated at http://www.flexboxpatterns.com and https://github.com/cjcenizal/flexbox-patterns/blob/master/README.md#things-to-keep-in-mind.
